version: "3.9"

# Declaro los servicios a utilizar
services:

  # Servicio de base de datos
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-okteto:/var/lib/postgresql/data
    
    
  # Servicio de backend
  backend:
    build: .
    env_file:
      - .env
    restart: on-failure
    ports:
      - 8001:8001
    volumes:
      - ./app:/usr/src/app/app
      - ./routers:/usr/src/app/routers

    
  # Servicio de pgAdmin web
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5555
    ports:
      - "80:5555"
    depends_on:
      - postgres
      
networks:
  default:
    name: postgre-service_default
volumes:
  postgres-okteto:
  app:
  routers: